### ISSUE TITLE
Where is Infoblox.psm1 module?

### ISSUE THREAD

**Issue by KurtDeGreeff** [murrahjm/Infoblox-Classy#4]
I don't see Infoblox.psm1 , you maybe forgot to include it..?

Many thanks for this great module

**Comment by murrahjm** [comment]
I actually put the psm1 together during the build, found it easier to work with separate files.  If you just want the complete module you can find it on the powershell gallery here:  https://www.powershellgallery.com/packages/InfobloxCmdlets/1.1.51
