### ISSUE TITLE
Keep getting error 400 as I am not using WAPI version v2.2

### ISSUE THREAD

**Issue by fabienmazieres** [murrahjm/Infoblox-Classy#5]
Hi,

It seems the variable $Global:WapiVersion never gets updated when you create the session as I keep getting error 400:
New-IBWebSession -Gridmaster $ibx_server -Credential $ibx_credential -WapiVersion "v1.4.2"
Get-IBNetwork -Gridmaster $ibx_server -Credential $ibx_credential -Network "10.255.0.0/16"

Give me this error:
Get-IBNetwork : Unable to connect to Infoblox device ipam.apmoller.net.  Error code:  
Microsoft.PowerShell.Commands.WriteErrorException: Unable to connect to Infoblox device 
ipam.apmoller.net.  Error code:  System.Net.WebException: The remote server returned an error: (400) 
Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Users\fma146\OneDrive - Maersk Group\PowerShell\ReadInfoBlox - InfobloxCmdlets.ps1:24 char:1
+ Get-IBNetwork -Gridmaster $ibx_server -Credential $ibx_credential -Ne ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-IBNetwork

Now the last commend with -Verbose returns the following:
VERBOSE: GET-IBNETWORK:  Beginning Function
VERBOSE: Existing session to ipam.apmoller.net found
VERBOSE: GET-IBNETWORK:  Connecting to Infoblox device ipam.apmoller.net to retrieve Views
VERBOSE: GET-IBVIEW:  Beginning Function
VERBOSE: Existing session to ipam.apmoller.net found
VERBOSE: GET-IBVIEW:  calling IB_NetworkView Get method with the following parameters:
VERBOSE: GET-IBVIEW:  ,,,False,0
VERBOSE: URI String:  https://ipam.apmoller.net/wapi/**v2.2**/networkview?_return_fields=extattrs,name,is_
default,comment
VERBOSE: GET https://ipam.apmoller.net/wapi/v2.2/networkview?_return_fields=extattrs,name,is_default,c
omment with 0-byte payload

**Comment by fabienmazieres** [comment]
My solution as I did not want to change all reference to global by a script variable.
New-IBWebSession.ps1:
    If ($WapiVersion){$Global:WapiVersion = $WapiVersion}
    $URI = "https://$gridmaster/wapi/$Global:WapiVersion/grid"

Better solution would be to setup a script variable like for the Rest session and grid master details
By the way, getting side tracked here a bit but script variable could solve the issue with self-signed certificate as mentionned in Issue[ #2 Add support for SkipSslValidation](https://github.com/murrahjm/Infoblox-Classy/issues/2)

**Comment by murrahjm** [comment]
the global wapiversion was code that predated the whole websession thing.  looks like a pretty simple oversight, I'll see about changing that to a script variable, that should be a relatively easy fix.

**Comment by fabienmazieres** [comment]
Ok I figured it out I think, I just pushed the change.

I think more work is needed to clean-up the code and use Script variable rather than the Global Variable, I thought of a few more enhancement that I will propose.

Closing this issue, Thanks!
