### ISSUE TITLE
Add-IBExtensibleAttribute error: "Modifier + not allowed for extattrs"

### ISSUE THREAD

**Issue by fabienmazieres** [murrahjm/Infoblox-Classy#6]
Hi,

Add-IBExtensibleAttribute returns an error on my IPAM v1.4.2:
URL: https://{{IpamIp}}/wapi/v1.4.2/network/ZG5zLm5ldHdvcmskMTAuMjU1LjIzLjEyOC8
yNi8w:10.255.23.128/26/default
Body:
```
{
	"extattrs+":  {
                  "SiteCode":  {
                                   "value":  "test"
                               }
              }
}
```

Response:
```
{
    "Error": "AdmConProtoError: Modifier + not allowed for extattrs",
    "code": "Client.Ibap.Proto",
    "text": "Modifier + not allowed for extattrs"
}
```

The following is working (without +)
```
{
	"extattrs":  {
                  "SiteCode":  {
                                   "value":  "DKCPH65"
                               }
              }
}
```

**Comment by fabienmazieres** [comment]
v1.4 does not allow + for ext attributes so that means I cannot add attributes one by one, I must be able to pass all of them at once.
If you give me access to the code, I can push a patch that would allow to pass a list of arguments to the function so you can push multiple attributes at once.

**Comment by murrahjm** [comment]
most of my work has been with v2.2, so I guess that's something they changed at some point.  Seems simple enough, would just have to get any existing attributes on the object, append to the list then push the whole thing.  the code is all here, feel free to do a pull request with the fix in it if you have it written up.

**Comment by fabienmazieres** [comment]
I am a bit new to GitHub, and when I tried to create a pull request it told me I had no permissions for it.
Do you need to add me to collaborators?

**Comment by murrahjm** [comment]
patch looks promising, might need some tweaks.  for easier organization I'm going to branch this off for further testing, and put master back to the pre-merge commit.  Also I put in a fix to the issue you closed about the wapi version not being respected.  It appears to be working now though since i did all the development at v2.2 I suspect there will be a few other code incompatibilities at version 1.4.2.

**Comment by fabienmazieres** [comment]
I did some testing and with the patches I provided I could get the network data as well as pushing the attributes so I am confident that there should not be that many incompatibility.
I did fork the project on my account so I will be working there and maybe you can keep this new branch active for me to push future change, it would make thing easier for both of us. 

Closing the issue as I have got the code working on my side

**Comment by murrahjm** [comment]
great!  yeah I'll leave it as an open branch for the time being.  at some point I'd like to find a way for both options to coexist in every class, perhaps without having to select the correct option in the cmdlet.  I'd also like to maybe have tests that can test functionality across different wapi versions.
